"""Agrega campo dispositivo a usuario

Revision ID: 23cfa8b9f23b
Revises: 32f5e72380c4
Create Date: 2025-07-10 15:22:56.634854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cfa8b9f23b'
down_revision = '32f5e72380c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispositivo', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('dispositivo')

    # ### end Alembic commands ###
