"""Agregar campo observacion a Despacho

Revision ID: 534549846e07
Revises: cfca08e5050b
Create Date: 2025-07-31 19:34:10.626717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534549846e07'
down_revision = 'cfca08e5050b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despacho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=True))

    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.drop_column('observacion')

    with op.batch_alter_table('despacho', schema=None) as batch_op:
        batch_op.drop_column('observacion')

    # ### end Alembic commands ###
