"""Usuario sin verificacion de dispositivo

Revision ID: bbb6bc48d4fc
Revises: 23cfa8b9f23b
Create Date: 2025-07-11 11:50:35.308707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb6bc48d4fc'
down_revision = '23cfa8b9f23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('dispositivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispositivo', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
