"""Agregar columna correo al modelo Usuario

Revision ID: c2f62fb2efc1
Revises: 727535696fef
Create Date: 2025-07-10 10:48:25.595070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f62fb2efc1'
down_revision = '727535696fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
